"use client";
// AI4 UI: one-click VoC report generation + a list of saved past reports.
import { useEffect, useState } from "react";
import { useSession } from "next-auth/react";

export default function ReportsPage() {
  const { data: session } = useSession();
  const canGenerate = session?.user?.role === "ADMIN" || session?.user?.role === "ANALYST";

  const [reports, setReports] = useState<any[]>([]);
  const [selected, setSelected] = useState<any>(null);
  const [generating, setGenerating] = useState(false);
  const [loading, setLoading] = useState(true);

  function load() {
    fetch("/api/reports").then((r) => r.json()).then((data) => { setReports(data); setLoading(false); });
  }
  useEffect(load, []);

  async function generate() {
    setGenerating(true);
    const res = await fetch("/api/reports", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ periodDays: 7 }),
    });
    const report = await res.json();
    setGenerating(false);
    load();
    setSelected(report);
  }

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <h1 className="text-2xl font-bold">Voice-of-Customer Reports</h1>
        {canGenerate && (
          <button onClick={generate} disabled={generating} className="bg-brand text-white rounded-lg px-4 py-2 text-sm font-medium disabled:opacity-50">
            {generating ? "Generating..." : "Generate report (last 7 days)"}
          </button>
        )}
      </div>

      {loading ? (
        <p className="text-gray-500">Loading...</p>
      ) : reports.length === 0 && !selected ? (
        <div className="bg-white border rounded-xl p-10 text-center text-gray-500">
          No reports yet. Generate your first weekly digest above.
        </div>
      ) : (
        <div className="grid grid-cols-3 gap-6">
          <div className="col-span-1 bg-white border rounded-xl divide-y">
            {reports.map((r) => (
              <button key={r.id} onClick={() => setSelected(r)} className="w-full text-left p-3 text-sm hover:bg-gray-50">
                <div className="font-medium">{r.title}</div>
                <div className="text-xs text-gray-400">{new Date(r.createdAt).toLocaleString()}</div>
              </button>
            ))}
          </div>

          <div className="col-span-2 bg-white border rounded-xl p-6">
            {selected ? (
              <ReportView report={selected} />
            ) : (
              <p className="text-gray-400 text-sm">Select a report to view it.</p>
            )}
          </div>
        </div>
      )}
    </div>
  );
}

function ReportView({ report }: { report: any }) {
  const c = report.contentJson;
  return (
    <div className="space-y-4">
      <div>
        <h2 className="font-bold text-lg">{report.title}</h2>
        <p className="text-xs text-gray-400">Generated by {report.generatedBy?.name}</p>
      </div>
      <p className="text-sm text-gray-700">{c.summary}</p>

      <div>
        <h3 className="font-semibold text-sm mb-2">Recommended actions</h3>
        <ul className="list-disc list-inside text-sm space-y-1">
          {c.recommendedActions?.map((a: string, i: number) => <li key={i}>{a}</li>)}
        </ul>
      </div>

      <div>
        <h3 className="font-semibold text-sm mb-2">Top themes</h3>
        <ul className="text-sm space-y-1">
          {c.topThemes?.map((t: any) => (
            <li key={t.name}>{t.name} — {t.count} items ({t.deltaVsPrevious >= 0 ? "+" : ""}{t.deltaVsPrevious}%)</li>
          ))}
        </ul>
      </div>

      <div>
        <h3 className="font-semibold text-sm mb-2">Representative quotes</h3>
        <ul className="text-sm space-y-1 text-gray-600 italic">
          {c.sampleQuotes?.map((q: string, i: number) => <li key={i}>"{q}"</li>)}
        </ul>
      </div>

      <p className="text-xs text-gray-400 pt-4 border-t">
        Tip: use your browser's Print → Save as PDF to export this report (brief AI4.3).
      </p>
    </div>
  );
}
